# Generated by Django 5.1.5 on 2025-08-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_siteconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
