# Generated by Django 5.1.5 on 2025-08-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_siteconfig_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={},
        ),
        migrations.AddField(
            model_name='produto',
            name='trailer',
            field=models.CharField(blank=True, help_text='ID do YouTube (exemplo: dQw4w9WgXcQ)', max_length=50, null=True),
        ),
    ]
